# Generated by Django 5.2.1 on 2025-06-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_citysearch_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citysearch',
            name='session_id',
        ),
    ]
