# Generated by Django 5.2.1 on 2025-06-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_remove_citysearch_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='citysearch',
            name='session_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
